import { AlertTriangle, BookOpen, CheckCircle2, ChevronDown, Search, SlidersHorizontal, Stethoscope } from "lucide-react";
import { useMemo, useState } from "react";
import { postParameterCategoryLabels, postParameterTerms, postProblemCategoryLabels, postProblemRecipes, type PostParameterCategory, type PostProblemCategory } from "../../data/postParameterGlossary.js";

export function PostGlossary() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<PostParameterCategory | "all">("all");
  const [openId, setOpenId] = useState("highlights");
  const [view, setView] = useState<"terms" | "diagnosis">("terms");
  const [problemCategory, setProblemCategory] = useState<PostProblemCategory | "all">("all");
  const [openRecipeId, setOpenRecipeId] = useState(postProblemRecipes[0]?.id ?? "");
  const filtered = useMemo(() => postParameterTerms.filter((item) => (category === "all" || item.category === category) && `${item.term} ${item.full} ${item.purpose} ${item.example} ${item.page}`.toLowerCase().includes(query.trim().toLowerCase())), [category, query]);
  const categoryCounts = useMemo(() => Object.fromEntries(Object.keys(postParameterCategoryLabels).map((key) => [key, postParameterTerms.filter((item) => item.category === key).length])), []);
  const problemFiltered = useMemo(() => postProblemRecipes.filter((item) => problemCategory === "all" || item.category === problemCategory), [problemCategory]);
  const openParameter = (parameterId: string) => { const parameter = postParameterTerms.find((item) => item.id === parameterId); if (!parameter) return; setQuery(parameter.term); setCategory("all"); setOpenId(parameter.id); setView("terms"); };
  return <section className="post-workspace post-glossary"><header><div><p className="eyebrow">POST PARAMETER LIBRARY</p><h2>达芬奇后期参数词典</h2><p>不是只解释名词，而是说明“往哪边调、画面发生什么、为什么这样调”。示例针对4K驾驶、树林溪流、城市夜景、HDR10和环境音。</p></div><BookOpen size={28} /></header>
    <div className="post-glossary-summary"><span><strong>{postParameterTerms.length}</strong>个核心参数</span><span><strong>{postProblemRecipes.length}</strong>套问题配方</span><span><strong>调高 / 调低</strong>双向解释</span><span><strong>实拍案例</strong>与风险边界</span></div>
    <nav className="post-glossary-view-tabs"><button className={view === "terms" ? "active" : ""} onClick={() => setView("terms")}><BookOpen size={14} />参数词典<small>理解单个控制</small></button><button className={view === "diagnosis" ? "active" : ""} onClick={() => setView("diagnosis")}><Stethoscope size={14} />问题诊断<small>按症状找调整顺序</small></button></nav>
    {view === "terms" ? <><div className="post-glossary-toolbar"><label><Search size={15} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索高光、阴影、降噪、曲线、LUFS、HDR标签…" /></label><nav><button className={category === "all" ? "active" : ""} onClick={() => setCategory("all")}>全部 <small>{postParameterTerms.length}</small></button>{(Object.entries(postParameterCategoryLabels) as [PostParameterCategory,string][]).map(([key,label]) => <button key={key} className={category === key ? "active" : ""} onClick={() => setCategory(key)}>{label}<small>{categoryCounts[key]}</small></button>)}</nav></div>
    <div className="post-parameter-list">{filtered.map((item) => { const open = openId === item.id; return <article key={item.id} className={open ? "open" : ""}><button onClick={() => setOpenId(open ? "" : item.id)}><span><small>{postParameterCategoryLabels[item.category]} · {item.page}</small><strong>{item.term}</strong><p>{item.full}｜{item.purpose}</p></span><ChevronDown size={16} /></button>{open && <div className="post-parameter-detail"><section><h4><SlidersHorizontal size={13} />调整方向</h4><dl><div><dt>调高 / 增加</dt><dd>{item.increase}</dd></div><div><dt>调低 / 减少</dt><dd>{item.decrease}</dd></div></dl></section><section className="example"><h4>你的拍摄案例</h4><p>{item.example}</p><strong>为什么这样调</strong><p>{item.why}</p></section><aside><small>避免误用</small><p>{item.caution}</p></aside></div>}</article>; })}</div>{!filtered.length && <p className="post-empty">没有找到匹配参数，请尝试“亮度”“夜景”“噪声”或切换分类。</p>}</> : <section className="post-diagnosis"><nav><button className={problemCategory === "all" ? "active" : ""} onClick={() => setProblemCategory("all")}>全部问题 <small>{postProblemRecipes.length}</small></button>{(Object.entries(postProblemCategoryLabels) as [PostProblemCategory,string][]).map(([key,label]) => <button key={key} className={problemCategory === key ? "active" : ""} onClick={() => setProblemCategory(key)}>{label}<small>{postProblemRecipes.filter((item) => item.category === key).length}</small></button>)}</nav><div>{problemFiltered.map((recipe) => { const open = openRecipeId === recipe.id; return <article key={recipe.id} className={open ? "open" : ""}><button onClick={() => setOpenRecipeId(open ? "" : recipe.id)}><span><small>{postProblemCategoryLabels[recipe.category]} · {recipe.scene}</small><strong>{recipe.symptom}</strong><p>{recipe.diagnosis}</p></span><ChevronDown size={16} /></button>{open && <div className="post-recipe-detail"><aside><small>先观察</small>{recipe.observe.map((item) => <span key={item}>{item}</span>)}</aside><ol>{recipe.steps.map((step,index) => { const parameter = postParameterTerms.find((item) => item.id === step.parameterId); return <li key={step.parameterId}><b>{index + 1}</b><div><button onClick={() => openParameter(step.parameterId)}>{parameter?.term ?? step.parameterId}</button><strong>{step.action}</strong><p>{step.reason}</p></div></li>; })}</ol><footer><p><CheckCircle2 size={14} /><span><small>停止条件</small>{recipe.stopWhen}</span></p><p><AlertTriangle size={14} /><span><small>不要这样做</small>{recipe.avoid}</span></p></footer></div>}</article>; })}</div></section>}
  </section>;
}
