import { AlertTriangle, BookOpen, Camera, Check, ChevronRight, Clapperboard, ClipboardCheck, Film, Headphones, ListChecks, ShieldCheck, Sparkles, Workflow } from "lucide-react";
import { useState } from "react";
import { usePlannerStore } from "../../app/store.js";
import { longformBlueprints, longformEditWarnings, longformFormats, longformPhases, longformQualityGates } from "../../data/longformProduction.js";
import { Documentary90Tutorial } from "./Documentary90Tutorial.js";
import { FormatProcessTutorial } from "./FormatProcessTutorial.js";

type Workspace = "formats" | "production" | "shooting" | "blueprint" | "editing" | "quality";
export function LongformGuideView() {
  const setView = usePlannerStore((state) => state.setView);
  const [workspace, setWorkspace] = useState<Workspace>("formats");
  const [formatId, setFormatId] = useState(longformFormats[0]!.id);
  const [phaseId, setPhaseId] = useState(longformPhases[0]!.id);
  const format = longformFormats.find((item) => item.id === formatId)!;
  const phase = longformPhases.find((item) => item.id === phaseId)!;
  const blueprint = longformBlueprints.find((item) => item.formatId === formatId)!;
  return <main className="longform-page"><header className="longform-head"><div><p className="eyebrow">LONGFORM PRODUCTION</p><h1>长片制作指南</h1><p>纪录片、电影式旅行、沉浸环境与公路散文，从选题、拍摄到剪辑交付的完整方法。</p></div><dl><div><dt>长片类型</dt><dd>{longformFormats.length}</dd></div><div><dt>制作阶段</dt><dd>{longformPhases.length}</dd></div><div><dt>核心原则</dt><dd>真实 · 连续 · 可验证</dd></div></dl></header>
    <nav className="longform-tabs"><button className={workspace === "formats" ? "active" : ""} onClick={() => setWorkspace("formats")}><Film size={17} /><span>类型方法<small>先决定观众承诺</small></span></button><button className={workspace === "production" ? "active" : ""} onClick={() => setWorkspace("production")}><Workflow size={17} /><span>完整流程<small>从选题到归档</small></span></button><button className={workspace === "shooting" ? "active" : ""} onClick={() => setWorkspace("shooting")}><Camera size={17} /><span>拍摄设计<small>画面、声音与安全</small></span></button><button className={workspace === "blueprint" ? "active" : ""} onClick={() => setWorkspace("blueprint")}><BookOpen size={17} /><span>实战蓝图<small>采访、章节与拍摄日</small></span></button><button className={workspace === "editing" ? "active" : ""} onClick={() => setWorkspace("editing")}><Clapperboard size={17} /><span>剪辑诊断<small>问题、原因与修正</small></span></button><button className={workspace === "quality" ? "active" : ""} onClick={() => setWorkspace("quality")}><ClipboardCheck size={17} /><span>交付质检<small>事实、声画与归档</small></span></button></nav>
    {workspace === "formats" && <><section className="longform-formats"><nav>{longformFormats.map((item) => <button key={item.id} className={item.id === format.id ? "active" : ""} onClick={() => setFormatId(item.id)}><small>{item.english}</small><strong>{item.name}</strong><span>{item.duration}</span></button>)}</nav><article><header><div><small>{format.english}</small><h2>{format.name}</h2><p>{format.promise}</p></div><span>{format.duration}</span></header><div className="longform-format-grid"><section><h3><Sparkles size={15} />叙事结构</h3><ol>{format.structure.map((item,index) => <li key={item}><span>{index + 1}</span>{item}</li>)}</ol></section><section><h3><Camera size={15} />拍摄方法</h3><ul>{format.shooting.map((item) => <li key={item}><Check size={13} />{item}</li>)}</ul></section><section><h3><Clapperboard size={15} />剪辑方法</h3><ul>{format.editing.map((item) => <li key={item}><Check size={13} />{item}</li>)}</ul></section><aside><h3><AlertTriangle size={15} />高风险问题</h3>{format.risks.map((item) => <p key={item}>{item}</p>)}</aside></div></article></section>{format.id === "documentary" ? <Documentary90Tutorial openCameraLibrary={() => setView("cameras")} openPostWorkflow={() => setView("post")} /> : <FormatProcessTutorial format={format} blueprint={blueprint} />}</>}
    {workspace === "production" && <section className="longform-production"><nav>{longformPhases.map((item,index) => <button key={item.id} className={item.id === phase.id ? "active" : ""} onClick={() => setPhaseId(item.id)}><span>{String(index + 1).padStart(2,"0")}</span><strong>{item.name}</strong></button>)}</nav><article><header><small>阶段输出</small><h2>{phase.name}</h2><p>{phase.output}</p></header><div><section><h3>必须完成</h3><ol>{phase.tasks.map((item,index) => <li key={item}><span>{index + 1}</span>{item}</li>)}</ol></section><aside><h3><ShieldCheck size={15} />进入下一阶段前确认</h3>{phase.checks.map((item) => <p key={item}><Check size={13} />{item}</p>)}</aside></div><footer><button onClick={() => setView("projects")}>打开视频项目工作台<ChevronRight size={14} /></button></footer></article></section>}
    {workspace === "shooting" && <section className="longform-shooting"><header><div><p className="eyebrow">COVERAGE SYSTEM</p><h2>长片拍摄覆盖模型</h2><p>每一个重要场景都要能回答“在哪里、谁在做什么、关键细节是什么、发生了什么变化、如何结束”。</p></div><Camera size={28} /></header><div className="coverage-sequence">{[["01","建立","地点、时间、天气、方向"],["02","行动","人物或车辆完整动作"],["03","关系","主体与环境的中景"],["04","细节","手、工具、路牌、纹理"],["05","反应","人物、环境或结果变化"],["06","结束","动作完成或离开画面"]].map(([number,title,note]) => <article key={number}><span>{number}</span><strong>{title}</strong><p>{note}</p></article>)}</div><div className="longform-sound-safety"><section><Headphones size={20} /><div><h3>声音必须单独设计</h3><p>主声、环境声、Room Tone、过渡声和音乐不是同一件事。每个地点至少录制60秒纯环境声；纪录采访要同时监听主声和备份声道。</p></div></section><section><ShieldCheck size={20} /><div><h3>真实性与安全优先</h3><p>不能为了镜头让驾驶者操作设备，不能让被摄者重复危险动作，也不能用剪辑伪造事件因果。敏感素材和肖像授权必须可追溯。</p></div></section></div><footer><button onClick={() => setView("cameras")}>打开相机参数库</button><button onClick={() => setView("plans")}>建立拍摄计划</button></footer></section>}
    {workspace === "blueprint" && <section className="longform-blueprint"><header><div><p className="eyebrow">PRODUCTION BLUEPRINT</p><h2>{format.name}实战蓝图</h2><p>{blueprint.target}｜{blueprint.shootingRatio}</p></div><select value={formatId} onChange={(e) => setFormatId(e.target.value as typeof formatId)}>{longformFormats.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></header><aside className="blueprint-minimum"><ShieldCheck size={17} /><div><small>最低覆盖标准</small><p>{blueprint.minimumCoverage}</p></div></aside><div className="blueprint-chapters">{blueprint.chapterPlan.map((item) => <article key={item.range}><small>{item.range}</small><strong>{item.purpose}</strong><p>{item.material}</p></article>)}</div><div className="blueprint-grid"><section><h3>前期准备</h3>{blueprint.preparation.map((item) => <p key={item}><Check size={12} />{item}</p>)}</section><section><h3>采访与提问</h3>{blueprint.interviewQuestions.map((item) => <p key={item}><span>Q</span>{item}</p>)}</section><section><h3>声音计划</h3>{blueprint.soundPlan.map((item) => <p key={item}><Headphones size={12} />{item}</p>)}</section><section><h3>拍摄日顺序</h3>{blueprint.shootingDay.map((item,index) => <p key={item}><span>{index + 1}</span>{item}</p>)}</section></div><section className="blueprint-edit-passes"><h3>剪辑版本迭代</h3><div>{blueprint.editPasses.map((item,index) => <article key={item.name}><span>{String(index + 1).padStart(2,"0")}</span><strong>{item.name}</strong><p>{item.goal}</p><small>不要：{item.doNot}</small></article>)}</div></section></section>}
    {workspace === "editing" && <section className="longform-editing"><header><div><p className="eyebrow">EDIT DIAGNOSIS</p><h2>长片剪辑常见问题</h2><p>不要只问“哪里剪短”，先判断缺的是信息、行动、空间、声音还是结构变化。</p></div><ListChecks size={28} /></header><div>{longformEditWarnings.map(([problem,signal,fix],index) => <article key={problem}><span>{String(index + 1).padStart(2,"0")}</span><div><small>问题</small><h3>{problem}</h3><p>{signal}</p></div><aside><small>修正方向</small><p>{fix}</p></aside></article>)}</div><footer><button onClick={() => setView("post")}>进入达芬奇后期流程<ChevronRight size={14} /></button></footer></section>}
    {workspace === "quality" && <section className="longform-quality"><header><div><p className="eyebrow">FINAL QUALITY GATES</p><h2>发布前完整质检</h2><p>质检不是最后随便看一遍，而是分别验证故事、事实、连续性、声音、色彩、字幕和可恢复性。</p></div><ClipboardCheck size={28} /></header><div>{longformQualityGates.map((gate,index) => <article key={gate.category}><header><span>{String(index + 1).padStart(2,"0")}</span><h3>{gate.category}</h3><small>{gate.items.length}项</small></header>{gate.items.map((item) => <p key={item}><Check size={12} />{item}</p>)}</article>)}</div><aside><AlertTriangle size={18} /><p><strong>任何一项发现事实错误、隐私风险、离线媒体、削波、错误HDR标签或授权不明，都应停止发布。</strong>先回到对应制作阶段修正，再重新进行相关质检。</p></aside><footer><button onClick={() => setView("post")}>打开后期执行清单</button><button onClick={() => setView("upload")}>检查上传参数</button></footer></section>}
  </main>;
}
