import { Calculator, Camera, CheckCircle2, CloudRain, HardDrive, Lightbulb, Save, SlidersHorizontal, SunMedium } from "lucide-react";
import { useMemo, useState } from "react";
import type { CameraPreset } from "../../types/domain.js";
import { estimateNdStops, flickerSafeShutters, recordingMinutesForStorage, recordingStorageGb, recommendPreset, shutterForFps, type SceneGeneratorInput } from "../../services/cameraDecisionService.js";

export function CameraDecisionTools({ presets, onSelectPreset }: { presets: CameraPreset[]; onSelectPreset: (id: string) => void }) {
  const devices = ["全部设备", ...new Set(presets.map((item) => item.camera))];
  const [input, setInput] = useState<SceneGeneratorInput>({ device: "全部设备", light: "day", movement: "drive", weather: "clear", nd: true, delivery: "hdr10", sound: "ambience" });
  const [fps, setFps] = useState(30);
  const [ev, setEv] = useState(4);
  const [bitrate, setBitrate] = useState(100);
  const [duration, setDuration] = useState(90);
  const [storage, setStorage] = useState(128);
  const [mainsHz, setMainsHz] = useState<50 | 60>(50);
  const result = useMemo(() => recommendPreset(presets, input), [input, presets]);
  const deviceCapabilities = useMemo(() => devices.slice(1).map((device) => {
    const own = presets.filter((item) => item.camera === device);
    return { device, maxFps: Math.max(...own.map((item) => item.settings.fps)), resolutions: [...new Set(own.map((item) => item.settings.resolution))], profiles: [...new Set(own.map((item) => item.settings.profile).filter(Boolean))], color: [...new Set(own.map((item) => item.settings.colorDepth).filter(Boolean))], scenes: new Set(own.map((item) => item.scene)).size };
  }), [devices, presets]);
  const update = <K extends keyof SceneGeneratorInput>(key: K, value: SceneGeneratorInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  return <section className="camera-tools-workspace"><header><div><p className="eyebrow">DECISION ASSISTANT</p><h2>场景参数生成器</h2><p>先找到最接近的预设，再给出现场调整；结果是拍摄起点，不代替波形图、斑马线和短片回放。</p></div><SlidersHorizontal size={29} /></header>
    <div className="camera-generator-layout"><form><label>设备<select value={input.device} onChange={(e) => update("device", e.target.value)}>{devices.map((item) => <option key={item}>{item}</option>)}</select></label><label>光线<select value={input.light} onChange={(e) => update("light", e.target.value as SceneGeneratorInput["light"])}><option value="day">白天</option><option value="night">夜间</option><option value="blue-hour">蓝调时刻</option></select></label><label>机位<select value={input.movement} onChange={(e) => update("movement", e.target.value as SceneGeneratorInput["movement"])}><option value="drive">车载移动</option><option value="walk">步行移动</option><option value="tripod">固定机位</option></select></label><label>天气<select value={input.weather} onChange={(e) => update("weather", e.target.value as SceneGeneratorInput["weather"])}><option value="clear">晴朗</option><option value="cloudy">阴天</option><option value="rain">雨天</option></select></label><label>交付<select value={input.delivery} onChange={(e) => update("delivery", e.target.value as SceneGeneratorInput["delivery"])}><option value="hdr10">HDR10</option><option value="sdr">Rec.709 SDR</option></select></label><label>声音<select value={input.sound} onChange={(e) => update("sound", e.target.value as SceneGeneratorInput["sound"])}><option value="ambience">真实环境音</option><option value="music">音乐+环境声</option></select></label><button type="button" className={input.nd ? "active" : ""} onClick={() => update("nd", !input.nd)}><SunMedium size={15} />ND滤镜：{input.nd ? "有" : "无"}</button></form>
      <article className="camera-generator-result">{result ? <><header><Camera size={22} /><div><small>推荐起点</small><h3>{result.preset.camera}</h3><p>{result.preset.scene}</p></div><button onClick={() => onSelectPreset(result.preset.id)}>打开完整预设</button></header><div className="camera-result-values"><span><small>画幅</small>{result.preset.settings.resolution}</span><span><small>帧率</small>{result.preset.settings.fps} FPS</span><span><small>快门</small>{result.preset.settings.shutter}</span><span><small>ISO</small>{result.preset.settings.iso.min}–{result.preset.settings.iso.max}</span></div><ol>{result.adjustments.map((item) => <li key={item}><CheckCircle2 size={14} />{item}</li>)}</ol></> : <p>当前条件没有可用预设。</p>}</article></div>
    <div className="camera-calculators"><article><Calculator size={20} /><div><h3>180°快门换算</h3><p>输入拍摄帧率，得到自然运动模糊的起始快门。</p></div><label><input type="number" min="1" max="240" value={fps} onChange={(e) => setFps(Number(e.target.value) || 1)} />FPS</label><output>{shutterForFps(fps)}</output></article><article><CloudRain size={20} /><div><h3>ND档位辅助</h3><p>测光比目标亮多少EV，就从相近档位开始。</p></div><label><input type="number" min="0" max="10" step="0.3" value={ev} onChange={(e) => setEv(Number(e.target.value) || 0)} />EV</label><output>ND {estimateNdStops(ev)}档</output></article><article><HardDrive size={20} /><div><h3>容量与录制时长</h3><p>按视频码率估算，不包含格式化损耗及额外音轨。</p></div><div className="camera-calc-fields"><label><input type="number" min="1" value={bitrate} onChange={(e) => setBitrate(Number(e.target.value) || 1)} />Mbps</label><label><input type="number" min="1" value={duration} onChange={(e) => setDuration(Number(e.target.value) || 1)} />分钟</label><label><input type="number" min="1" value={storage} onChange={(e) => setStorage(Number(e.target.value) || 1)} />GB</label></div><output>{recordingStorageGb(bitrate, duration).toFixed(1)}GB<br /><small>{storage}GB约录{Math.floor(recordingMinutesForStorage(storage, bitrate))}分钟</small></output></article><article><Lightbulb size={20} /><div><h3>防频闪快门</h3><p>市电灯光下优先测试这些快门，最终以试录回放为准。</p></div><div className="camera-frequency-switch"><button className={mainsHz === 50 ? "active" : ""} onClick={() => setMainsHz(50)}>50Hz</button><button className={mainsHz === 60 ? "active" : ""} onClick={() => setMainsHz(60)}>60Hz</button></div><output>{flickerSafeShutters(fps, mainsHz).join(" · ")}</output></article></div>
    <aside className="camera-pipeline-guide"><Save size={18} /><div><strong>不要混淆四层参数</strong><p>相机采集（XAVC / S-Log3 / 4:2:2 10-bit）→ Resolve时间线（Rec.2100 PQ）→ HDR母版（HEVC Main10）→ 平台转码（播放端VP9/AV1/HEVC）。</p></div></aside>
    <section className="camera-device-capabilities"><header><div><small>MY DEVICES</small><h3>设备能力摘要</h3></div><p>根据当前参数库中已经验证和使用的组合汇总，不代表厂商规格表中的全部极限模式。</p></header><div>{deviceCapabilities.map((item) => <article key={item.device}><Camera size={18} /><div><h4>{item.device}</h4><p>{item.resolutions.join(" · ")} · 最高已用 {item.maxFps} FPS</p><span>{item.profiles.length ? item.profiles.join(" · ") : "标准色彩"}</span><span>{item.color.length ? item.color.join(" · ") : "色深待补充"}</span><small>{item.scenes}种场景方案</small></div></article>)}</div></section>
  </section>;
}
